#!/bin/sh
killall Xvfb x11ibm eventmap

Xvfb \
	-retro \
	-ac \
	-screen 0 640x370x8 \
	-fbdir /tmp/ \
	+extension XTEST \
	&

sleep 5

export DISPLAY=:0

xterm -fg white -bg black -geometry +10+10 &

./x11ibm /tmp/Xvfb_screen0 &
./eventmap /dev/ttyACM0 &
